### ISSUE TITLE
Definition of MNIST_model1() missing

### ISSUE THREAD

**Issue by josejuanhm** [vlsi-lab/MARLIN#1]
Hello MARLIN developers,

When trying to run the riscv_characterization/NSGA2/nsga.py script, the error "name 'MNIST_model1' is not defined" is thrown. Should it be defined by another script within the MARLIN folders? I am guessing a .pth file within neural_networks/models may be used to initialize the model variable in the script throwing the error, which instead calls MNIST_model1(), but this function is not defined anywhere.

Which information am I missing? Thanks in advance for the support.

**Comment by flague** [comment]
Hello,

Thank you for spotting something was missing. Now, the model architecture has been uploaded in `neural_networks/MNIST/mnist_net.py`, so that it can be correctly instantiated. 
Notice that when executing nsga.py, you should start from a pre-trained model, so, as you said, a .pth file is also needed and it should be the output produced by NEMO.
